language: java
dist: trusty

jdk:
    - openjdk11

matrix:
  fast_finish: true
  include:
     - jdk: openjdk11

script:
    -  gradle all

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install gradle
